### ISSUE TITLE
Remove all 'any' types

### ISSUE THREAD

**Issue by AndreasWintherMoen** [ntnu-informatikk-2021/SDG-ontology-visualizer#24]
We have taken a few shortcuts and set types as 'any' here and there. This is bad practice and should be avoided.

**Comment by vemund0507** [comment]
There is some 'any' types in [this](https://github.com/ntnu-informatikk-2021/SDG-ontology-visualizer/blob/main/frontend/src/api/ontologies.ts) file.

**Comment by erikskaar** [comment]
I think it's nice to have this issue open to remind ourselves to go over our code and remove all `any` that we can find =)
